# Common Functions
from Functions.Data_Loader import sql_query_runner  
from Functions.State_Map import state_map 
# import inflection

# Introduction Page Functions
from Functions.Inroduction_Page_Map import quarterly_india_map_introduction_page


# Business Question 1 Functions
from Functions.Transaction_Dynamics.India_Map import quarterly_india_map
from Functions.Transaction_Dynamics.Top_10_States import top_10_states
from Functions.Transaction_Dynamics.Transaction_Payment_Method import trasaction_by_payment_method
from Functions.Transaction_Dynamics.Trend_Quarterly import quarterly_trend
from Functions.Transaction_Dynamics.State_Level_Transactions import state_level_transaction

# Question 2 Engagement Analysis
from Functions.Engagement_Analysis.Brandwise_Engagement import brand_user_engagement
from Functions.Engagement_Analysis.Statwise_Transaction import brand_statewise

# Question 3 Insurance Analysis
from Functions.Insurance_Trend.insurance_trend import insurance_trend_india_map
from Functions.Insurance_Trend.insurance_over_years import insurance_trend
from Functions.Insurance_Trend.Quarterly_Trend import insurance_trend_quarterly

# Question 4 Insurance Engagement
from Functions.Insurance_Engagement.Engagement_Across_States import insurance_engagement
from Functions.Insurance_Engagement.Engagement_Trend import insurance_trend_districts

# Top Performing States and Districts
from Functions.Top_Performing.top_districts import top_10_districts
from Functions.Top_Performing.top_states import top_states
from Functions.Top_Performing.top_10_pincodes import top_10_pincodes
from Functions.Top_Performing.top_10_trend import top_10_trend